### ISSUE TITLE
segfault on socket.py line 110

### ISSUE THREAD

**Issue by julienfr112** [wrobell/aionn#3]
> line /usr/local/lib/python3.5/dist-packages/nnpy/errors.py 6
> return /usr/local/lib/python3.5/dist-packages/nnpy/errors.py 6
> return /usr/local/lib/python3.5/dist-packages/aionn/socket.py 157
> line /usr/local/lib/python3.5/dist-packages/aionn/socket.py 110
> 
> Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
> 0x00007ffff43bfff6 in nn_getl (buf=0xfffffffffffffffc <error: Cannot access memory at address 0xfffffffffffffffc>)
>     at /home/julien/Projets/neverchatalone/nanomsg/src/utils/wire.c:45
> 45	    return (((uint32_t) buf [0]) << 24) |
> (gdb) bt
> #0  0x00007ffff43bfff6 in nn_getl (buf=0xfffffffffffffffc <error: Cannot access memory at address 0xfffffffffffffffc>)
>     at /home/julien/Projets/neverchatalone/nanomsg/src/utils/wire.c:45
> #1  0x00007ffff43bd19b in nn_chunk_getptr (p=0x0) at /home/julien/Projets/neverchatalone/nanomsg/src/utils/chunk.c:211
> #2  0x00007ffff43bcf88 in nn_chunk_free (p=0x0) at /home/julien/Projets/neverchatalone/nanomsg/src/utils/chunk.c:150
> #3  0x00007ffff43b18bd in nn_freemsg (msg=0x0) at /home/julien/Projets/neverchatalone/nanomsg/src/core/global.c:368
> #4  0x00007ffff45fad3c in _cffi_f_nn_freemsg (self=<optimized out>, arg0=<optimized out>) at build/temp.linux-x86_64-3.5/_nnpy.c:843
> #5  0x00000000005204db in call_function (oparg=<optimized out>, pp_stack=0x7fffffffd430) at ../Python/ceval.c:4690
> #6  PyEval_EvalFrameEx () at ../Python/ceval.c:3236

 If the call is successful the user is responsible for deallocating the message using the nn_freemsg(3) function in http://nanomsg.org/v0.1/nn_recv.3.html

**Comment by julienfr112** [comment]
#4 seems to fix it (no random segfault any more)

**Comment by julienfr112** [comment]
fixed #4
